const Strings = {
  requestTimeoutMessage:
    'It looks like the request is taking longer than expected time. Please check your internet connectivity and try again.',
  somethingWentWrong: 'Something went wrong.',
  serverErrorMessage:
    "it looks like we're encountering server errors. We'll be back up soon. Sorry!",
  tokenExpireMessage:
    'Your access token has expired. Please try to login again.',
  noInternetConnection: 'No Internet Connection',
  pleaseCheckYourInnternet: 'Please check your internet connection',
  height: 'Height',
  meters: 'meters',
  mass: 'Mass',
  kg: 'kg',
  creationDate: 'Date of Creation',
  numberOfFilms: 'Number of Films The Person Appears In',
  birthYear: 'Birth Year',
  homeWorldName: 'Home World Name',
  terrain: 'Terrain',
  climate: 'Climate',
  amountOfResidents: 'Amount of Residents',
  search: 'Search...',
  noRecordFound: 'No Record Found.',
  loginTitle: 'Login to your account',
  loginDescription: 'Enter your credentials below to log in to the platform',
  email: 'Email',
  password: 'Password',
  emailPlaceholder: 'Enter Email',
  passwordPlaceholder: 'Enter Password',
  login: 'Login',
  enterEmailMsg: 'Please enter email address',
  enterValidEmailMsg: 'Please enter valid email address',
  enterPasswordMsg: 'Please enter password',
  enterValidPasswordMsg:
    'Password must be between 8 and 20 characters and have at least one digit.',
  loginSuccess: 'You have logged in successfully',
  logOut: 'Log Out',
  logoutMessage: 'Are you sure you want to log out?',
  yes: 'Yes',
  no: 'No',
  logoutSuccess: 'You have logged out successfully',
  tokenRefreshSuccessFully: 'Token refreshed successfully',
  home: 'Home',
  filter: 'Filter',

  homeWold: 'Home Wolrd',
  films: 'Films',
  species: 'Species',
  starShips: 'Star Ships',
  apply: 'Apply',
  result: 'Result',
};
export default Strings;
